// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOgVpNQQpce3IzbwpqlJqSu3KWv_NHz5w',
    appId: '1:241178671335:web:8165f25e627399407cca42',
    messagingSenderId: '241178671335',
    projectId: 'sync-play-12c04',
    authDomain: 'sync-play-12c04.firebaseapp.com',
    storageBucket: 'sync-play-12c04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJsEqc0wxo3wvuFMjkIxTNsSenT51o4f0',
    appId: '1:241178671335:android:d4029b216bb033a17cca42',
    messagingSenderId: '241178671335',
    projectId: 'sync-play-12c04',
    storageBucket: 'sync-play-12c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTDaf_jtf99Ub6F_9xMumzgLMyyldNAsA',
    appId: '1:241178671335:ios:549d22dba6490af37cca42',
    messagingSenderId: '241178671335',
    projectId: 'sync-play-12c04',
    storageBucket: 'sync-play-12c04.firebasestorage.app',
    iosBundleId: 'com.example.syncplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTDaf_jtf99Ub6F_9xMumzgLMyyldNAsA',
    appId: '1:241178671335:ios:549d22dba6490af37cca42',
    messagingSenderId: '241178671335',
    projectId: 'sync-play-12c04',
    storageBucket: 'sync-play-12c04.firebasestorage.app',
    iosBundleId: 'com.example.syncplay',
  );
}
